src/UserBundle/Entity/User.php
<?php

namespace UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\HttpFoundation\File\File;
use GlobalBundle\Service\Upload;

/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="UserBundle\Repository\UserRepository")
 * @UniqueEntity(fields="email", message="user.validators.uniqueemail")
 * @UniqueEntity(fields="username", message="user.validators.uniquepseudonyme")
 * @ORM\HasLifecycleCallbacks
 */
class User implements AdvancedUserInterface, \Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var date
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var date
     *
     * @ORM\Column(name="changed", type="datetime", nullable=true)
     */
    private $changed;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=255, unique=true)
     * @Assert\NotBlank(message="user.validators.pseudonyme")
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     * @Assert\NotBlank(message="user.validators.nom")
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=255)
     * @Assert\NotBlank(message="user.validators.prenom")
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=64)
     * @Assert\NotBlank(message="user.validators.password")
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, unique=true)
     * @Assert\NotBlank(message="user.validators.email")
     * @Assert\Email(message="user.validators.emailvalide")
     */
    private $email;

    /**
     * @var bool
     *
     * @ORM\Column(name="isActive", type="boolean")
     */
    private $isActive;

    /**
     * @var array
     *
     * @ORM\Column(name="roles", type="array")
     * @Assert\NotBlank(message="user.validators.rolemin")
     */
    private $roles = array();

    /**
     * @Assert\Image(
        minWidth = 150,
        maxWidth = 150,
        minHeight = 150,
        maxHeight = 150,
        mimeTypes = {"image/jpeg", "image/png"}),
        maxSize = "1M"
     */
    private $file;

    /**
     * @var string
     * @ORM\Column(name="avatar", type="string", length=255, nullable=true)
     */
    private $avatar;

    /* Configuration */
    public function __construct(){
        $this->isActive = false;
        $this->created = new \DateTime();
        $this->roles = array('ROLE_USER');
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     *
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     *
     * @return User
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * Retourne 1 si actif 0 si pas actif
     */
    public function reverseState()
    {
        $etat = $this->getIsActive();

        return !$etat;
    }

    /**
     * Get isActive
     *
     * @return bool
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->nom,
            $this->prenom,
            $this->password,
            $this->isActive,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->nom,
            $this->prenom,
            $this->password,
            $this->isActive,
        ) = unserialize($serialized);
    }
    
   public function getRoles()
    {
        return $this->roles;
    }

    public function eraseCredentials()
    {
    }

    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    /**
     * Set roles
     *
     * @param array $roles
     *
     * @return User
     */
    public function setRoles($roles)
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return User
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set changed
     *
     * @param \DateTime $changed
     *
     * @return User
     */
    public function setChanged($changed)
    {
        $this->changed = $changed;

        return $this;
    }

    /**
     * Get changed
     *
     * @return \DateTime
     */
    public function getChanged()
    {
        return $this->changed;
    }

    /**
     * @ORM\PreUpdate()
     */
    public function preChanged()
    {
        $this->changed = new \DateTime();
    }

    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->isActive;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile(File $file = null)
    {
        $this->file = $file;
        if (null !== $this->avatar){
            $this->avatar = null;
        }

        $this->file = $file;
    }

    /**
     * Set avatar
     *
     * @param string $avatar
     *
     * @return User
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * Get avatar
     *
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    public function uploadAvatar()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (is_null($this->file)) {
            return;
        }

        // On récupère le nom original du fichier de l'internaute
        $upload = new Upload();
        $name = $upload->createName(
            $this->file->getClientOriginalName(),
            $this->getUploadRootDir().'/'
        );

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move($this->getUploadRootDir(), $name);

        /* On enregistre le nom de l'image dans l'entité */
        $this->avatar = $name;
    }

    /**
     * Retourne le chemin relatif de l'image pour le navigateur
     */
    public function getUploadDir()
    {
        return 'img/user/avatar';
    }

    /**
     * On retourne le chemin relatif vers l'image pour notre code PHP
     */
    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../web/'.$this->getUploadDir();
    }


    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return User
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     *
     * @return User
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }
}

src/UserBundle/Resources/views/Admin/ajouter.html.twig
{% extends "GlobalBundle:Admin/Layout:layout.html.twig" %}

{% block contentTitre %}Ajouter un utilisateur{% endblock %}

{% block content %}
	{{ form_start(form, {'attr': {'class': 'form-horizontal', novalidate: 'novalidate'}}) }}

		{{ form_errors(form) }}
		
		{{ form_label(form.username, "Pseudonyme *") }}
		{{ form_errors(form.username) }}
		{{ form_widget(form.username, {'attr': {'class': 'form-elem big'}}) }}

        {{ form_label(form.nom, "Nom *") }}
        {{ form_errors(form.nom) }}
        {{ form_widget(form.nom, {'attr': {'class': 'form-elem big'}}) }}

        {{ form_label(form.prenom, "Prénom *") }}
        {{ form_errors(form.prenom) }}
        {{ form_widget(form.prenom, {'attr': {'class': 'form-elem big'}}) }}

		{{ form_label(form.email, "Email *") }}
		{{ form_errors(form.email) }}
		{{ form_widget(form.email, {'attr': {'class': 'form-elem big'}}) }}

		{{ form_label(form.roles, "Rôles *") }}
		{{ form_errors(form.roles) }}
		<div class="liste big">
            {{ form_widget(form.roles) }}
		</div>

		{{ form_label(form.file, "Avatar") }}
		{{ form_errors(form.file) }}
		{{ form_widget(form.file, {'attr': {'class': 'form-elem big'}}) }}
		<div class="form-legende">
			L'image doit faire exactement 150px par 150px<br>Le format doit être (jpg, png)<br>Le poid ne doit pas dépacer 1Mo
		</div>

		{{ form_errors(form.password) }}
		{{ form_widget(form.password) }}

		{{ form_widget(form.Enregistrer, {'attr': {'class': 'form-submit medium turquoise'}}) }}
		
		{{ form_rest(form) }}

	{{ form_end(form) }}
{% endblock %}

src/UserBundle/Resources/views/Admin/compteModifier.html.twig
{% extends "GlobalBundle:Admin/Layout:layout.html.twig" %}

{% block contentTitre %}Mes informations{% endblock %}

{% block cssBefore %}
    <link href="{{ asset('js/sweet/sweet.css')}}" rel="stylesheet" type="text/css">
{% endblock %}

{% block breadcrumb %}
	<div id="breadcrumb">
		{{ include("GlobalBundle:Admin/Include:breadcrumb.html.twig", {'breadcrumb':breadcrumb }) }}
	</div>
{% endblock %}

{% block content %}
	{{ form_start(form, {'attr': {'class': 'form-horizontal', novalidate: 'novalidate'}}) }}

		{{ form_errors(form) }}

		{{ form_label(form.username, "Pseudonyme *") }}
		{{ form_errors(form.username) }}
		{{ form_widget(form.username, {'attr': {'class': 'form-elem big'}}) }}

        {{ form_label(form.nom, "Nom *") }}
        {{ form_errors(form.nom) }}
        {{ form_widget(form.nom, {'attr': {'class': 'form-elem big'}}) }}

        {{ form_label(form.prenom, "Prénom *") }}
        {{ form_errors(form.prenom) }}
        {{ form_widget(form.prenom, {'attr': {'class': 'form-elem big'}}) }}

		{{ form_label(form.email, "Email *") }}
		{{ form_errors(form.email) }}
		{{ form_widget(form.email, {'attr': {'class': 'form-elem big'}}) }}

		{{ form_label(form.roles, "Rôles *") }}
		{{ form_errors(form.roles) }}
		{{ form_widget(form.roles, {'attr': {'class': 'liste big'}}) }}

        {% if utilisateur.avatar is not empty %}
            <div id="ajaxImage1">
                <div class="form-image big">
                    <img src="{{ asset(utilisateur.uploadDir ~ '/' ~  utilisateur.avatar) }}">
                    <br>
                    <a href="{{ path('admin_user_supprimer_avatar',{'id': utilisateur.id})}}" class="btn rouge sweetDeleteImage" data-parent="ajaxImage1"><i class="fa fa-trash"></i> Supprimer</a>
                </div>
            </div>
        {% endif %}

		{{ form_label(form.file, "Avatar") }}
		{{ form_errors(form.file) }}
		{{ form_widget(form.file, {'attr': {'class': 'form-elem big'}}) }}
		<div class="form-legende">
			L'image doit faire exactement 150px par 150px<br>Le format doit être (jpg, png)<br>Le poid ne doit pas dépacer 1Mo
		</div>

	{{ form_end(form) }}
{% endblock %}

{% block scriptBefore %}
    <script type="text/javascript" src="{{ asset('js/sweet/sweet.js')}}"></script>
{% endblock %}

src/UserBundle/Resources/views/Admin/comptePassword.html.twig
{% extends "GlobalBundle:Admin/Layout:layout.html.twig" %}

{% block contentTitre %}Mon mot de passe{% endblock %}

{% block breadcrumb %}
	<div id="breadcrumb">
		{{ include("GlobalBundle:Admin/Include:breadcrumb.html.twig", {'breadcrumb':breadcrumb }) }}
	</div>
{% endblock %}

{% block content %}
	{{ form_start(form, {'attr': {'class': 'form-horizontal', novalidate: 'novalidate'}}) }}

		{{ form_errors(form) }}
		{{ form_rest(form) }}

	{{ form_end(form) }}
{% endblock %}

src/UserBundle/Resources/views/Admin/historique.html.twig
{% extends "GlobalBundle:Admin/Layout:layout.html.twig" %}

{% block contentTitre %}Gestion des historiques{% endblock %}

{% block content %}
	<table class="table">
		
		<tr>
            <th width="3%"></th>
            <th width="1%"></th>
            <th class="left" width="56%">Historique</th>
            <th width="20%">Utilisateur</th>
            <th width="20%">Ip</th>
		</tr>

		{% for historique in historiques %}

			<tr>

                {% if historique.utilisateur is not empty %}
                    <td class="turquoise"></td>
                {% else %}
                    <td class="rouge"></td>
                {% endif %}

                <td></td>

				<td class="left">
					<p class="tableDate">Ajouté le {{ historique.created|date("d/m/Y à H:i") }}</p>
					{% if historique.changed is not null %}
						<p class="tableDate">Modifié le {{ historique.changed|date("d/m/Y à H:i") }}</p>
					{% endif %}
					<p>{{ historique.contenu }}</p>
				</td>

                <td>
                    {% if historique.utilisateur is not empty %}
                        <p>{{ historique.utilisateur.prenom }} {{ historique.utilisateur.nom }}</p>
                    {% endif %}
                </td>

                <td>
                    <p>{{ historique.ip }}</p>
                </td>

			</tr>

		{% else %}
			<tr>
				<td colspan="5">Aucun historique</td>
			</tr>
		{% endfor %}

	</table>
{% endblock %}

src/UserBundle/Resources/views/Admin/manager.html.twig
{% extends "GlobalBundle:Admin/Layout:layout.html.twig" %}

{% block contentTitre %}Gestion des utilisateurs{% endblock %}

{% block content %}
	<div id="recherche">
		<form action="{{ path('admin_user_manager') }}" method="post">
			<input type="text" name="username" class="form-elem medium" value="{{ recherches.username | default('') }}">

			<button type="submit" name="addRecherche"><i class="fa fa-search"></i></button>
		</form>
	</div>

	<table class="table">
		
		<tr>
			<th width="12%"></th>
			<th class="left" width="43%">Utilisateur</th>
			<th width="30%">Rôles</th>
			<th colspan="3" width="15%">Actions</th>
		</tr>

		{% for utilisateur in pagination %}
			
			<tr>

				<td>
					{% if utilisateur.avatar %}
						<img class="tableImage" src="{{ asset(utilisateur.uploadDir ~ '/' ~  utilisateur.avatar) }}">
					{% else %}
						<i class="tableAltIcon fa fa-user"></i>
					{% endif %}
				</td>

				<td class="left">
					<p class="tableDate">Ajouté le {{ utilisateur.created|date("d/m/Y à H:i") }}</p>
					{% if utilisateur.changed is not null %}
						<p class="tableDate">Modifié le {{ utilisateur.changed|date("d/m/Y à H:i") }}</p>
					{% endif %}
					<p><strong>{{ utilisateur.nom }} {{ utilisateur.prenom }}</strong></p>
					<p><a href="mailto:{{ utilisateur.email }}">{{ utilisateur.email }}</a></p>
				</td>

				<td>
					{% for role in utilisateur.roles %}
						{% if role == 'ROLE_ADMIN' %} 
							<p>Administrateur</p>
						{% elseif role == 'ROLE_USER' %}
							<p>Utilisateur</p>
						{% endif %}
					{% endfor %}
				</td>

				{% if utilisateur.isActive == false %}
					<td data-url="{{ path('admin_user_publier',{'id': utilisateur.id})}}" class="tablePublucation">
                    	<a href="{{ path('admin_user_publier',{'id': utilisateur.id})}}" title="Publication"><i class="tableAction rouge fa fa-check"></i></a>
                    </td>
				{% else %}
					<td data-url="{{ path('admin_user_publier',{'id': utilisateur.id})}}" class="tablePublucation">
                    	<a href="{{ path('admin_user_publier',{'id': utilisateur.id})}}" title="Publication"><i class="tableAction turquoise fa fa-check"></i></a>
                    </td>
				{% endif %}

				<td>
                	<a href="{{ path('admin_user_modifier_password',{'id': utilisateur.id})}}" title="Modifier le mot de passe"><i class="tableAction fa fa-unlock-alt"></i></a>
                </td>

				<td>
                    <a href="{{ path('admin_user_modifier',{'id': utilisateur.id})}}" title="Modifier l'utilisateur"><i class=" tableAction fa fa-pencil"></i></a>
                </td>

			</tr>

		{% else %}
			<tr>
				<td colspan="6">Aucun utilisateur</td>
			</tr>
		{% endfor %}

	</table>

	{# display navigation #}
	<div class="navigation">
	    {{ knp_pagination_render(pagination) }}
	</div>

{% endblock %}

src/UserBundle/Resources/views/Admin/modifier.html.twig
{% extends "GlobalBundle:Admin/Layout:layout.html.twig" %}

{% block contentTitre %}Modifier l'utilisateur : {{ utilisateur.username}} {% endblock %}

{% block breadcrumb %}
	<div id="breadcrumb">
		{{ include("GlobalBundle:Admin/Include:breadcrumb.html.twig", {'breadcrumb':breadcrumb }) }}
	</div>
{% endblock %}

{% block content %}

	{{ form_start(form, {'attr': {'class': 'form-horizontal', novalidate: 'novalidate'}}) }}

		{{ form_errors(form) }}

		{{ form_label(form.username, "Pseudonyme *") }}
		{{ form_errors(form.username) }}
		{{ form_widget(form.username, {'attr': {'class': 'form-elem big'}}) }}

        {{ form_label(form.nom, "Nom *") }}
        {{ form_errors(form.nom) }}
        {{ form_widget(form.nom, {'attr': {'class': 'form-elem big'}}) }}

        {{ form_label(form.prenom, "Prénom *") }}
        {{ form_errors(form.prenom) }}
        {{ form_widget(form.prenom, {'attr': {'class': 'form-elem big'}}) }}

		{{ form_label(form.email, "Email *") }}
		{{ form_errors(form.email) }}
		{{ form_widget(form.email, {'attr': {'class': 'form-elem big'}}) }}

		{{ form_label(form.roles, "Rôles *") }}
		{{ form_errors(form.roles) }}
		<div class="liste big">
			{{ form_widget(form.roles) }}
		</div>

        {% if utilisateur.avatar is not empty %}
            <div id="ajaxImage1">
                <div class="form-image big">
                    <img src="{{ asset(utilisateur.uploadDir ~ '/' ~  utilisateur.avatar) }}">
                    <br>
                    <a href="{{ path('admin_user_supprimer_avatar',{'id': utilisateur.id})}}" class="btn rouge sweetDeleteImage" data-parent="ajaxImage1"><i class="fa fa-trash"></i> Supprimer</a>
                </div>
            </div>
        {% endif %}

		{{ form_label(form.file, "Avatar") }}
		{{ form_errors(form.file) }}
		{{ form_widget(form.file, {'attr': {'class': 'form-elem big'}}) }}
		<div class="form-legende">
			L'image doit faire exactement 150px par 150px<br>Le format doit être (jpg, png)<br>Le poid ne doit pas dépacer 1Mo
		</div>

		{{ form_widget(form.Enregistrer, {'attr': {'class': 'form-submit medium turquoise'}}) }}

		{{ form_rest(form) }}

	{{ form_end(form) }}
{% endblock %}

src/UserBundle/Resources/views/Admin/modifierPassword.html.twig
{% extends "GlobalBundle:Admin/Layout:layout.html.twig" %}

{% block contentTitre %}Modifier le mot de passe de : {{ utilisateur.username}} {% endblock %}

{% block breadcrumb %}
	<div id="breadcrumb">
		{{ include("GlobalBundle:Admin/Include:breadcrumb.html.twig", {'breadcrumb':breadcrumb }) }}
	</div>
{% endblock %}

{% block content %}
	{{ form_start(form, {'attr': {'class': 'form-horizontal', novalidate: 'novalidate'}}) }}

		{{ form_errors(form) }}

		{{ form_errors(form.password) }}
		{{ form_widget(form.password) }}

		{{ form_widget(form.Enregistrer, {'attr': {'class': 'form-submit medium turquoise'}}) }}

		{{ form_rest(form) }}

	{{ form_end(form) }}
{% endblock %}